global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitoring'
      send_resolved: true
      icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
      title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}Alerte sur {{ .CommonLabels.job }}{{ end }}
      text: >-
        {{ range .Alerts -}}
        *Alerte:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Détails:* {{ .Annotations.description }}
        *Durée:* {{ .StartsAt | since }}
        {{ if ne .GeneratorURL "" }}*Source:* [{{ .GeneratorURL }}]({{ .GeneratorURL }}){{ end }}
        {{ end }}

  - name: 'slack-critical'
    slack_configs:
    - channel: '#alerts-critical'
      send_resolved: true
      icon_emoji: ':red_circle:'
      title: |-
        [URGENT] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}Alerte critique sur {{ .CommonLabels.job }}{{ end }}
      text: >-
        {{ range .Alerts -}}
        *Alerte:* {{ .Annotations.title }}
        *Détails:* {{ .Annotations.description }}
        *Durée:* {{ .StartsAt | since }}
        {{ if ne .GeneratorURL "" }}*Source:* [{{ .GeneratorURL }}]({{ .GeneratorURL }}){{ end }}
        {{ end }}

  - name: 'slack-warnings'
    slack_configs:
    - channel: '#alerts-warnings'
      send_resolved: true
      icon_emoji: ':warning:'
      title: |-
        [AVERTISSEMENT] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}Alerte sur {{ .CommonLabels.job }}{{ end }}
      text: >-
        {{ range .Alerts -}}
        *Alerte:* {{ .Annotations.title }}
        *Détails:* {{ .Annotations.description }}
        *Durée:* {{ .StartsAt | since }}
        {{ if ne .GeneratorURL "" }}*Source:* [{{ .GeneratorURL }}]({{ .GeneratorURL }}){{ end }}
        {{ end }}
