apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0

  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus_uid
          matcherRegex: "logger=(\\w+)"
          name: "Logger"
          url: "/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22%7Bjob%3D%5C%22$${__value.raw}%5C%22%7D%22%7D%5D"

  # PostgreSQL datasource (for application metrics)
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: gestionmax
    user: gestionmax
    editable: true
    secureJsonData:
      password: GestionMax2025!
    jsonData:
      sslmode: disable
      postgresVersion: 1500

  # Redis datasource (if metrics needed)
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: true
    secureJsonData:
      password: GestionMax2025!
